# Generated by Django 2.1.7 on 2019-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('Num_count', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Sexo', models.CharField(max_length=1)),
                ('Edad', models.IntegerField()),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Domicilio', models.TextField()),
            ],
        ),
    ]
